# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentatio


name: Build and Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow only when pushing to the main branch

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Or use '3.0' or '3.2' if you're unsure

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: uild the Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
